# Generated by Django 5.1.6 on 2025-05-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halalplace',
            name='category',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('market', 'Market'), ('mosque', 'Mosque'), ('prayer_room', 'Prayer Room')], max_length=20),
        ),
    ]
