# Generated by Django 5.1.6 on 2025-11-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_placeeditsuggestion_placeimagesuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimagesuggestion',
            name='original_image',
            field=models.ImageField(blank=True, help_text='Original uploaded image (without watermark)', null=True, upload_to='place_suggestions/originals/'),
        ),
        migrations.AlterField(
            model_name='placeimagesuggestion',
            name='image',
            field=models.ImageField(help_text='Watermarked image for display', upload_to='place_suggestions/'),
        ),
    ]
