# Generated by Django 5.1.6 on 2025-12-02 05:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_placeimagesuggestion_original_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('category_filter', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Search Query',
                'verbose_name_plural': 'Search Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='halalplace',
            name='name_korean',
            field=models.CharField(blank=True, db_index=True, help_text='Korean transliteration of English name for search', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='halalplace',
            name='name_romanized',
            field=models.CharField(blank=True, db_index=True, help_text='Romanized version of Korean name for search', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='halalplace',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, help_text='Full-text search vector for efficient searching', null=True),
        ),
        migrations.AlterField(
            model_name='halalplace',
            name='address',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='halalplace',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='halalplace',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='places_search_vector_idx'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='clicked_place',
            field=models.ForeignKey(blank=True, help_text='Place the user clicked from search results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_clicks', to='places.halalplace'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL),
        ),
    ]
