# Generated by Django 5.1.6 on 2025-12-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_enable_trigram_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProximityLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Location name in English (lowercase, e.g., 'hongdae', 'gangnam')", max_length=100, unique=True)),
                ('name_korean', models.CharField(blank=True, db_index=True, help_text="Location name in Korean (e.g., '홍대', '강남')", max_length=100, null=True)),
                ('aliases', models.JSONField(blank=True, default=list, help_text="Alternative names/spellings as JSON list (e.g., ['hongik', 'hongik university'])")),
                ('latitude', models.FloatField(help_text='Center latitude of this area')),
                ('longitude', models.FloatField(help_text='Center longitude of this area')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this location is searchable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proximity Location',
                'verbose_name_plural': 'Proximity Locations',
                'ordering': ['name'],
            },
        ),
    ]
