# Generated by Django 5.1.6 on 2026-01-04 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0008_proximity_locations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="halalplace",
            name="cached_average_rating",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=1,
                help_text="Cached average rating to avoid recalculating on every request",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="halalplace",
            name="cached_reviews_count",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Cached reviews count to avoid counting on every request",
            ),
        ),
        migrations.AddIndex(
            model_name="halalplace",
            index=models.Index(
                fields=["status", "created_at"], name="place_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="halalplace",
            index=models.Index(
                fields=["status", "category"], name="place_status_category_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="halalplace",
            index=models.Index(fields=["category"], name="place_category_idx"),
        ),
    ]
