# Generated by Django 5.1.6 on 2026-01-15 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0009_add_cached_rating_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="halalplace",
            name="temporary_closure_reason",
            field=models.CharField(
                blank=True,
                help_text="Reason for temporary closure (e.g., 'Renovation')",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="halalplace",
            name="temporary_closure_until",
            field=models.DateField(
                blank=True,
                help_text="Place is temporarily closed until this date",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="BusinessHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_24_hours",
                    models.BooleanField(
                        default=False, help_text="Open 24 hours, 7 days a week"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="Additional notes (e.g., 'Last order 30 min before close')",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "place",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_hours",
                        to="places.halalplace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Hours",
                "verbose_name_plural": "Business Hours",
            },
        ),
        migrations.CreateModel(
            name="BusinessHoursSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggested_hours",
                    models.JSONField(
                        help_text="Full weekly schedule as structured JSON"
                    ),
                ),
                (
                    "is_24_hours",
                    models.BooleanField(
                        default=False, help_text="Suggested as open 24 hours"
                    ),
                ),
                (
                    "suggested_notes",
                    models.CharField(
                        blank=True,
                        help_text="Suggested notes for business hours",
                        max_length=255,
                    ),
                ),
                ("reason", models.TextField(help_text="Why this change is needed")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hours_suggestions",
                        to="places.halalplace",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_hours_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suggested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hours_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Hours Suggestion",
                "verbose_name_plural": "Business Hours Suggestions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Day of the week (0=Monday, 6=Sunday)",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="Mark this day as closed (overrides time fields)",
                    ),
                ),
                (
                    "open_time",
                    models.TimeField(
                        blank=True,
                        help_text="Opening time in 24-hour format",
                        null=True,
                    ),
                ),
                (
                    "close_time",
                    models.TimeField(
                        blank=True,
                        help_text="Closing time in 24-hour format",
                        null=True,
                    ),
                ),
                (
                    "business_hours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="places.businesshours",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Slot",
                "verbose_name_plural": "Time Slots",
                "ordering": ["day_of_week", "open_time"],
            },
        ),
    ]
