# Generated by Django 5.1.6 on 2025-08-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ko', '한국어'), ('uz', "O'zbek")], default='en', max_length=2),
        ),
    ]
