# Generated by Django 5.1.6 on 2025-10-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="User's profile picture from social providers or uploaded manually", null=True, upload_to='users/profile_pictures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_avatar_url',
            field=models.URLField(blank=True, help_text="URL to user's avatar from social providers", null=True),
        ),
    ]
