# Generated by Django 5.1.6 on 2025-11-22 16:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Session ID for anonymous user tracking', max_length=100)),
                ('rating', models.IntegerField(choices=[(1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], help_text='User rating from 1-5 stars')),
                ('comment', models.TextField(blank=True, help_text='Optional detailed feedback comment', max_length=500)),
                ('page_url', models.CharField(max_length=500)),
                ('page_type', models.CharField(choices=[('home', 'Homepage'), ('explore', 'Explore Page'), ('place_detail', 'Place Detail'), ('prayer_times', 'Prayer Times'), ('blog', 'Blog'), ('submit', 'Submit Place'), ('other', 'Other')], max_length=50)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('time_on_site', models.IntegerField(help_text='Seconds spent on site before feedback')),
                ('time_on_page', models.IntegerField(help_text='Seconds on current page')),
                ('pages_visited', models.IntegerField(default=1)),
                ('scroll_depth', models.IntegerField(blank=True, help_text='Percentage of page scrolled (0-100)', null=True)),
                ('language', models.CharField(max_length=5)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('screen_resolution', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_category', models.CharField(blank=True, choices=[('ui_ux', 'UI/UX'), ('content', 'Content Quality'), ('bug', 'Bug Report'), ('feature', 'Feature Request'), ('positive', 'Positive Feedback'), ('negative', 'Complaint')], max_length=50)),
                ('admin_notes', models.TextField(blank=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_actionable', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback Response',
                'verbose_name_plural': 'Feedback Responses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='feedback_fe_created_050cd2_idx'), models.Index(fields=['rating'], name='feedback_fe_rating_a50455_idx'), models.Index(fields=['page_type'], name='feedback_fe_page_ty_d33d21_idx')],
            },
        ),
    ]
