# Generated by Django 5.1.6 on 2025-08-02 09:26

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=tinymce.models.HTMLField(help_text='Main content of the blog post with rich text formatting'),
        ),
    ]
