# Generated by Django 5.1.6 on 2026-01-04 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0009_add_cached_rating_fields"),
        ("reviews", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["place", "created_at"], name="review_place_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["user", "place"], name="review_user_place_idx"),
        ),
    ]
