# Generated by Django 5.1.6 on 2025-11-12 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('condition', models.CharField(choices=[('error_rate_above', 'Error Rate Above Threshold'), ('response_time_above', 'Response Time Above Threshold'), ('queue_age_above', 'Queue Age Above Threshold'), ('failed_login_spike', 'Failed Login Spike'), ('db_slow_queries', 'Database Slow Queries'), ('cache_hit_rate_below', 'Cache Hit Rate Below Threshold'), ('api_failure', 'External API Failure')], max_length=30)),
                ('threshold', models.FloatField(help_text='Threshold value for the condition')),
                ('window_minutes', models.IntegerField(default=10, help_text='Time window to evaluate the condition')),
                ('alert_channels', models.JSONField(default=list, help_text="List of alert channels: ['telegram', 'email', 'in_app']")),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.IntegerField(default=0)),
                ('cooldown_minutes', models.IntegerField(default=60, help_text='Minimum minutes between alerts for this rule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('metric_type', models.CharField(choices=[('request_count', 'Request Count'), ('error_count', 'Error Count'), ('avg_response_time', 'Average Response Time'), ('db_query_count', 'Database Query Count'), ('cache_hit_rate', 'Cache Hit Rate'), ('active_users', 'Active Users'), ('api_call_count', 'External API Call Count'), ('api_latency', 'External API Latency')], db_index=True, max_length=50)),
                ('metric_name', models.CharField(db_index=True, help_text='Specific metric identifier (e.g., endpoint path, API name)', max_length=100)),
                ('value', models.FloatField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Metric',
                'verbose_name_plural': 'System Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'metric_type', 'metric_name'], name='utils_syste_timesta_8ce699_idx'), models.Index(fields=['metric_type', 'timestamp'], name='utils_syste_metric__bf6192_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('archive', 'Archive'), ('bulk_action', 'Bulk Action')], db_index=True, max_length=20)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('object_repr', models.CharField(help_text='String representation of the object', max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Before/after values for updates')),
                ('ip_hash', models.CharField(db_index=True, max_length=16)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Admin Action',
                'verbose_name_plural': 'Admin Actions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'admin_user'], name='utils_admin_timesta_3dc534_idx'), models.Index(fields=['action_type', 'timestamp'], name='utils_admin_action__e1bc52_idx'), models.Index(fields=['admin_user', 'timestamp'], name='utils_admin_admin_u_da3b1c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('link', models.CharField(blank=True, help_text='Optional link to related page', max_length=500)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='Leave blank to send to all admins', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Notification',
                'verbose_name_plural': 'Admin Notifications',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['recipient', 'read', 'timestamp'], name='utils_admin_recipie_e19811_idx'), models.Index(fields=['severity', 'read'], name='utils_admin_severit_09bdf6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.CharField(choices=[('place', 'Halal Place'), ('review', 'Review'), ('blog', 'Blog Post'), ('suggestion', 'Edit Suggestion'), ('image_suggestion', 'Image Suggestion'), ('contact', 'Contact Message')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived'), ('pending', 'Set to Pending')], db_index=True, max_length=20)),
                ('time_in_queue_hours', models.FloatField(blank=True, help_text='Hours between submission and moderation', null=True)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for rejection')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Moderation Log',
                'verbose_name_plural': 'Content Moderation Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'moderator'], name='utils_conte_timesta_0bfd51_idx'), models.Index(fields=['action', 'timestamp'], name='utils_conte_action_a0a62f_idx'), models.Index(fields=['content_type', 'object_id'], name='utils_conte_content_ef9862_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField(db_index=True)),
                ('response_time_ms', models.FloatField(db_index=True, help_text='Response time in milliseconds')),
                ('is_staff', models.BooleanField(db_index=True, default=False)),
                ('ip_hash', models.CharField(db_index=True, help_text='Hashed IP address', max_length=16)),
                ('user_agent_hash', models.CharField(blank=True, help_text='Hashed user agent', max_length=16)),
                ('db_query_count', models.IntegerField(default=0)),
                ('cache_hits', models.IntegerField(default=0)),
                ('cache_misses', models.IntegerField(default=0)),
                ('error_type', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='utils_reque_timesta_9485ac_idx'), models.Index(fields=['status_code', 'timestamp'], name='utils_reque_status__ca4109_idx'), models.Index(fields=['response_time_ms'], name='utils_reque_respons_0f4e12_idx'), models.Index(fields=['is_staff', 'timestamp'], name='utils_reque_is_staf_5905bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('failed_login', 'Failed Login'), ('rate_limit_hit', 'Rate Limit Hit'), ('suspicious_activity', 'Suspicious Activity'), ('permission_denied', 'Permission Denied'), ('csrf_failure', 'CSRF Failure'), ('invalid_token', 'Invalid Token'), ('multiple_accounts', 'Multiple Accounts from Same IP')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=10)),
                ('ip_hash', models.CharField(db_index=True, max_length=16)),
                ('details', models.JSONField(default=dict, help_text='Additional context about the event')),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'event_type'], name='utils_secur_timesta_070e94_idx'), models.Index(fields=['severity', 'resolved', 'timestamp'], name='utils_secur_severit_f0b609_idx'), models.Index(fields=['event_type', 'timestamp'], name='utils_secur_event_t_ef7264_idx')],
            },
        ),
    ]
