# Generated by Django 5.1.6 on 2025-12-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='condition',
            field=models.CharField(choices=[('error_rate_above', 'Error Rate Above Threshold'), ('response_time_above', 'Response Time Above Threshold'), ('queue_age_above', 'Queue Age Above Threshold'), ('failed_login_spike', 'Failed Login Spike'), ('db_slow_queries', 'Database Slow Queries'), ('cache_hit_rate_below', 'Cache Hit Rate Below Threshold'), ('api_failure', 'External API Failure'), ('health_min_requests', 'Minimum Request Logs per Hour'), ('health_error_rate_warning', 'Health Check Error Rate Warning'), ('health_error_rate_critical', 'Health Check Error Rate Critical'), ('health_response_time_warning', 'Health Check Response Time Warning (ms)'), ('health_security_events_warning', 'Health Check Unresolved Security Events Warning')], max_length=30),
        ),
    ]
