# Generated by Django 5.1.6 on 2025-05-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerTimeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('prayer_times', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('calculation_method', models.IntegerField(default=3)),
                ('asr_method', models.IntegerField(default=1)),
            ],
            options={
                'indexes': [models.Index(fields=['city', 'country', 'date'], name='prayer_time_city_61c34a_idx'), models.Index(fields=['last_updated'], name='prayer_time_last_up_674e6f_idx')],
                'unique_together': {('city', 'country', 'date', 'calculation_method', 'asr_method')},
            },
        ),
    ]
