# Generated by Django 5.1.6 on 2026-02-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer_times', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamadanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Gregorian year (e.g. 2026)', unique=True)),
                ('hijri_year', models.IntegerField(help_text='Hijri year (e.g. 1447)')),
                ('start_date', models.DateField(help_text='First day of fasting per local authority (e.g. KMF)')),
                ('end_date', models.DateField(help_text='Last day of fasting')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text="e.g. 'Per KMF announcement on Feb 17'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ramadan Configuration',
                'verbose_name_plural': 'Ramadan Configurations',
                'ordering': ['-year'],
            },
        ),
    ]
